# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ssl : https://www.ibm.com/support/knowledgecenter/en/SSZHJ2_9.1.0/configuring/topics/usektool.html
server:
  session:
    timeout: 10
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: 1234567
    key-password: 123456
    key-store-type: JKS